### ISSUE TITLE
Generator fails to start - Block-scoped declarations

### ISSUE THREAD

**Issue by KerryRitter** [smartive/generator-giuseppe#3]
I tried to create a new workspace using yo giuseppe and got the following error:

```
C:\Workspaces\Spikes\test> yo giuseppe
C:\Users\kritter\AppData\Roaming\npm\node_modules\generator-giuseppe\app\index.js:8
class GiuseppeGenerator extends generators.Base {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as giuseppe:app] (C:\Users\kritter\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\kritter\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
    at Environment.get (C:\Users\kritter\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:260:16)
```

am i missing an install? i'm on node 4.4.5.

**Comment by buehler** [comment]
Hey @KerryRitter 
Yea.. you should use node 6 or higher :-)
I'd generally recommend it, since a lot of ES2015 features are supported now.

Hope I could help!
Cheers Chris

**Comment by KerryRitter** [comment]
Derr! Should have thought of that...

Anyway you guys could Babel it to support ES5? I'm stuck on v4 for the time being, and I think many others may be too.

**Comment by buehler** [comment]
Mhmm good question :-) I'll have a look at it.

**Comment by buehler** [comment]
As a sidenote, giuseppe itself is ES5 compatible. Only the generator is not.

**Comment by KerryRitter** [comment]
Right. That's why i kind of expected the generator to work with ES5 :D

**Comment by buehler** [comment]
@KerryRitter Alright, I rewrote the generator to typescript. It should be compatible after my buddy reviewed the code and we made the release.

**Comment by buehler** [comment]
@KerryRitter alright, it should be deployed :-)
